language: "en"

pipeline: spacy_sklearn

policies:
  - name: TEDPolicy
    epochs: 100
    max_history: 5
  - name: MemoizationPolicy
    max_history: 5


#    fallback_action_name: 'action_default_fallback'
