language: en
pipeline: spacy_sklearn
policies:
- name: TEDPolicy
  epochs: 100
  max_history: 5
- name: MemoizationPolicy
  max_history: 5
session_config:
  session_expiration_time: 10
  carry_over_slots_to_new_session: false
